# AVAS Config (Python-compatible)

policy = "paranoid"          # "paranoid", "normal", "sneaky", "logonly"
password = "quack"           # lowercase only (paranoid mode)
blacklist = ["Command Prompt", "Windows PowerShell"]  # list, not a string

# Advanced config
threshold = 30
size = 25
randdrop = 6
filename = "log.txt"
allow_auto_type_software = True
